name: organic_bloc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# (versionName)+(versionCode)
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #ui
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

  #injection:
  get_it: ^7.7.0

  #data:
  shared_preferences: ^2.2.3

  #state management:
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

  #model:
  equatable: ^2.0.5

  #api:
  dio: ^5.5.0+1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose

  #navigator:
  fluro: ^2.0.5


  lottie: ^3.1.2
  google_fonts: ^6.2.0
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1

  # Change language app
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/langs/
    - assets/images/loginbkg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
